### PR TITLE
image and input

### PR DESCRIPTION
**Pull request by preethasri**
created image and input component
image:
*square image
*round image
input:
*input with label
*error validation input
*radio input
*checkbox input

live link:https://deploy-preview-14--ornateui.netlify.app/images/image
live link:https://deploy-preview-14--ornateui.netlify.app/input/input

### CODE REVIEW

**Comment by preethasri** [comment]
https://deploy-preview-14--ornateui.netlify.app/images/image

**Comment by nshanbhag20001412** [comment]
hey before merging you need to get two approvals

**Comment by nshanbhag20001412** [comment]
hey before merging you need to get two peer aprrovals

**Comment by preethasri** [comment]
> hey before merging you need to get two approvals

Hii Neha sorry for that .  I am new to this PR thing and   I made some changes so i merged that and put this one here .

**Comment by nshanbhag20001412** [comment]
> > hey before merging you need to get two approvals
> 
> Hii Neha sorry for that. I am new to this PR thing and I made some changes so I merged that and put this one here.

can you contact some TA or someone who knows GitHub properly?. I'm really not sure how to resolve this

**Comment by preethasri** [comment]
> > > hey before merging you need to get two approvals
> > 
> > 
> > Hii Neha sorry for that. I am new to this PR thing and I made some changes so I merged that and put this one here.
> 
> can you contact some TA or someone who knows GitHub properly?. I'm really not sure how to resolve this

Thank you Neha for pointing it out . I will again create pull request

**Pull request merged**
